const names = {
   "Ana Paula Einsfeld": "C02",
   "Bruna Bortolatto": "C02",
   "Fernando Fagherazzi Pizzoli": "C02",
   "Gabrielli Selistre": "C02",
   "Isabeli Slongo Padilha": "C02",
   "Isadora Berton Corso": "C02",
   "Júlia Cristina Galvăo Ribas": "C02",
   "Marcella Finger Viezzer": "C02",
   "Maria Eduarda Gaiardo": "C02",
   "Pedro Schio Ferrigo": "C02",
   "Rafael Garcia Dias": "C02",
   "Valentina Viecelli Dornelles": "C02",
   "Vitória Luiza Cabral de Jesus": "C02",
   "Aleander Schuster de Almeida": "D03",
   "Ana Vitória Rodrigues": "D03",
   "Augusto Danieleski Tomanchievicz": "D03",
   "Bernardo Camargo Forini": "D03",
   "Cinara Camargo da Silva": "D03",
   "Eduarda Leite da Rosa": "D03",
   "Fernanda Marca": "D03",
   "Giovanna Caldas Lopes": "D03",
   "Isadora Manini Costa": "D03",
   "Laís Arruda Köche": "D03",
   "Laura Borges Cardoso": "D03",
   "Letícia Machado Gil": "D03",
   "Luísa dos Santos da Silva": "D03",
   "Manuella Pessoa Cavalcante da Costa": "D03",
   "Maria Eduarda Dannenhauer Uhl": "D03",
   "Maria Eduarda de Oliveira Biasuz": "D03",
   "Marina Cavion Lopes": "D03",
   "Paola Gregoletto Duso": "D03",
   "Pedro Augusto Pasa Sartori": "D03",
   "Sarah Luiza Azevedo da Silva": "D03",
   "Vicente Azevedo de Oliveira": "D03",
   "Anna Carolina Couto Leal": "A03",
   "Arthur da Fonseca Macedo": "A03",
   "Arthur Forni": "A03",
   "Augusto Branchi Graebin": "A03",
   "Augusto Moroni dos Santos": "A03",
   "Bernardo Azevedo Vieira": "A03",
   "Bianca Elisa Rossa": "A03",
   "Cristian Rafael Metz": "A03",
   "Enzo Matana da Silva": "A03",
   "Giovana Melos Borsoi": "A03",
   "Guilherme Augusto Velho de Oliveira": "A03",
   "Gustavo Carneiro dos Santos": "A03",
   "Henrique Brum Riva": "A03",
   "Janaína Giacomin": "A03",
   "Jean Vítor Dalla Vecchia Boniatti": "A03",
   "Joăo Victor Silveira Ferraz": "A03",
   "Johann Heckler Mota": "A03",
   "Júlia Giordano Bianchi": "A03",
   "Luís Henrique Bonetto": "A03",
   "Mariana Weschenfelder Glasenapp": "A03",
   "Maurício Bono Nunes": "A03",
   "Murilo Lazzari Gasperin": "A03",
   "Nicolas Schein Brakemeier": "A03",
   "Octavio Henrique Rodrigues Alves": "A03",
   "Pedro Henrique Negrini Perondi": "A03",
   "Vinícius Menegol Cardoso": "A03",
   "Yago Rech de Jesus": "A03",
   "Alana Pereira Pegoraro": "B03",
   "Augusto Henrique Cerutti": "B03",
   "Augusto Varisco Knapp": "B03",
   "Camila Brollo Macêdo": "B03",
   "Cláudia Oliveira da Cruz": "B03",
   "Daniel Damin Zamboni": "B03",
   "Diego Silveira da Silva": "B03",
   "Filipe Hrihorowitsch Scheid": "B03",
   "Gabriel Bado da Silva": "B03",
   "Gabriel Frizzo Ciervo": "B03",
   "Guilherme Scomazzon Tamagno": "B03",
   "Jhonatan de Lima de Almeida": "B03",
   "Joăo Henrique Camara Piccin": "B03",
   "Joăo Pedro de Castro Pereira": "B03",
   "João Pedro de Godoi da Silva": "B03",
   "Júlia Salvador Righez": "B03",
   "Leonardo Teles Cesar": "B03",
   "Leonora Sagas Rodrigues Viera": "B03",
   "Luana Reginato Bassanesi": "B03",
   "Lucca Marchett Frozza": "B03",
   "Maria Clara Sirtoli Lazaretti": "B03",
   "Maria Klein Pinheiro Machado": "B03",
   "Matheus Cassânego": "B03",
   "Matheus Concari Metz": "B03",
   "Miguel Valentini": "B03",
   "Natália de Azevedo": "B03",
   "Nícolas Buzin Gomes": "B03",
   "Nícolas Hunhoff Servelin": "B03",
   "Nicolas Menon Simiano": "B03",
   "Rayana Sofia Rizzi": "B03"	
}

export default names